[package]
name = "client"
version = "0.1.0"
edition = "2024"

[dependencies]
lazy_static = "1.5.0"
reqwest = {version = "0.12.28", features = ["blocking"]}
serde = "1.0.228"
serde_json = "1.0.148"
ui = { path = "../ui" }
shared = { path = "../shared" }
